### ISSUE TITLE
Array of Objects don't request an update

### ISSUE THREAD

**Issue by knuspertante** [adobe/lit-mobx#106] opened 2021-06-23 13:21 UTC
### Expected Behaviour
ComponentOne should rerender when todo array changed.

### Actual Behaviour
Changing the todo array in store class does not request a rerender in lit

### Reproduce Scenario (including but not limited to)
https://codesandbox.io/s/brave-panini-ozg2f?file=/src/component-one.ts

#### Steps to Reproduce
Switch from "second" page to "home" page and back again

Or add ${testString} after ${todoListTemplate} in ComponentOne render return statement. 

#### Platform and Version
Node 14.16.0
adobe/lit-mobx 1.0.1
lit 1.01
mobx 6.3.2

**Comment by knuspertante** [comment] 2021-06-23 13:53
I found the reason: 

"Make sure that an initial value is assigned to all state properties before calling makeAutoObservable(), otherwise the property will not be observable. This is a MobX limitation since we can’t use the TypeScript configuration "useDefineForClassFields": true due to conflict with Lit decorators mentioned above." 

For more information https://vaadin.com/docs/latest/fusion/application/state-management

Is it possible to add this to readme? 

Thx and nice work!

**Comment by StephenHaney** [comment] 2022-05-17 05:48
Agreed the readme should probably mention that `useDefineForClassFields` must be set to `false` for Lit.

However, this conflicts with MobX's requirement that `useDefineForClassFields` be set to `true`. You can still make MobX work with it set to `false`, but you need to be more careful to always assign values to your observable properties (if you don't assign an initial value, the property will not be observable). ~~And as far as I can tell, you can't use decorator syntax with MobX if `useDefineForClassFields` is `false.~~ Edit: decorators still work either way.

There's a thread here from a member of the Lit team asking MobX about this:
https://github.com/mobxjs/mobx/discussions/3216

**Comment by benjamind** [comment] 2022-05-18 14:37
Apologies I missed both these comments somehow.

@justinfagnani do you have any more insight as to the right outcome here given the conflicting requirements of mobx and lit in this case?

**Comment by justinfagnani** [comment] 2022-05-18 15:55
I think until standard decorators are available, or TypeScript adds the `accessor` keyword, we have a few workarounds:

1. Always assign an initial value to observable properties, even if `undefined`. This creates an instance property on the object that MobX can see and make observable.
2. Turn `useDefineForClassFields` on and use `declare` for reactive fields. [Example](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcblxuQGN1c3RvbUVsZW1lbnQoJ3NpbXBsZS1ncmVldGluZycpXG5leHBvcnQgY2xhc3MgU2ltcGxlR3JlZXRpbmcgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BwIHsgY29sb3I6IGJsdWUgfWA7XG5cbiAgQHByb3BlcnR5KClcbiAgZGVjbGFyZSBuYW1lO1xuICBcbiAgY29uc3RydWN0b3IoKSB7XG4gICAgc3VwZXIoKTtcbiAgICB0aGlzLm5hbWUgPSAnU29tZWJvZHknO1xuICB9XG5cbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYDxwPkhlbGxvLCAke3RoaXMubmFtZX0hPC9wPmA7XG4gIH1cbn1cbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2ltcGxlLWdyZWV0aW5nIG5hbWU9XCJXb3JsZFwiPjwvc2ltcGxlLWdyZWV0aW5nPlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ)
3. Turn `useDefineForClassFields` on and use `declare` for reactive fields and use the `static properties` field instead of decorators.

**Comment by benjamind** [comment] 2022-05-18 16:49
1 seems the simpler thing to suggest to consumers of the library?

So probably an update to the README to indicate why this shows up (due to the mismatch in `useDefineForClassFields` between MobX and Lit decorators. I guess the recommendation is to keep `useDefineForClassFields` to `false` so that lit works, and then just recommend our users always assign an initial value for observable properties then?

**Comment by StephenHaney** [comment] 2022-05-18 20:02
Thanks for all the info to everyone... I'll use option 2 personally as I'm not using reactive fields (or rarely) ~~That's probably the decision point — if you want to use MobX decorators, you have to use `useDefineForClassFields` set to `true` (as far as I can tell in testing).~~ Edit: part about decorators wasn't accurate.

**Comment by benjamind** [comment] 2022-05-18 20:06
This is whats confusing me, we're using both Mobx and Lit decorators at Adobe right now with this, so I'm unsure what we did to support that :-)

**Comment by StephenHaney** [comment] 2022-05-18 20:11
Oh interesting, what's your `useDefineForClassFields` setting? And are you on MobX 6? I'll keep toying around to see if I can figure out more as well.

**Comment by benjamind** [comment] 2022-05-18 20:25
On one app we're on Mobx5, but on the other we're on Mobx6 and have not specified a value for `useDefineForClassFields`, though I suspect we have always initialized properties with a default value.

**Comment by StephenHaney** [comment] 2022-05-19 04:14
Ok I need to walk back the bit about MobX decorators — I created a simple repro from scratch and with `useDefineForClassFields` set to `false`, MobX decorators still work as long as you assign an initial value to properties. Must be something else in my more complicated app that's breaking with `useDefineForClassFields` set to `false`. Editing my previous comments.

So my only observed drawback to the `false` config with MobX is that you must assign initial values to fields or they aren't made observable.

**Comment by benjamind** [comment] 2023-03-22 20:22
Thanks for hte update, closing this out then as not reproducible.

**Closed as completed by benjamind** 2023-03-22 20:22 UTC
